apiVersion: v1
kind: Service
metadata:
        name: {{ .Values.postgres.name }}-service
        labels:
                app: {{ .Values.postgres.name }}
        namespace: {{ .Values.namespace }}
spec:
        type: ClusterIP
        ports:
                - port: 5432
        selector:
                statefulset.kubernetes.io/pod-name: postgres-0
