apiVersion: apps/v1
kind: StatefulSet
metadata:
        name: {{ .Values.postgres.name }}
        namespace: {{ .Values.namespace }}
spec:
        serviceName: {{ .Values.postgres.name }}-service
        replicas: {{ .Values.postgres.replica }}
        selector:
                matchLabels:
                        app: {{ .Values.postgres.name }}
        template:
                metadata:
                        labels:
                                app: {{ .Values.postgres.name }}
                spec:
                        terminationGracePeriodSeconds: 10
                        containers:
                                - name: {{ .Values.postgres.name }}
                                  image: {{ .Values.postgres.image.name }}:{{ .Values.postgres.image.tag }}
                                  imagePullPolicy: "IfNotPresent"
                                  ports:
                                          - containerPort: 5432
                                  envFrom:
                                          - configMapRef:
                                                  name: {{ .Values.postgres.name }}-configmap
                                  env:
                                          - name: POSTGRES_USER
                                            valueFrom:
                                                    secretKeyRef:
                                                        name: {{ .Values.postgres.name }}-secret
                                                        key: username
                                          - name: POSTGRES_PASSWORD
                                            valueFrom:
                                                    secretKeyRef:
                                                        name: {{ .Values.postgres.name }}-secret
                                                        key: password
                                  volumeMounts:
                                          - mountPath: /var/lib/postgresql/data
                                            name: {{ .Values.postgres.name }}-data
                                            subPath: postgres
        volumeClaimTemplates:
                - metadata:
                          name: {{ .Values.postgres.name }}-data
                  spec:
                          accessModes: [ "ReadWriteOnce" ]
                          storageClassName: standard
                          resources:
                                  requests:
                                          storage: {{ .Values.postgres.volume.size }}
