apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  serviceName: {{ .Values.mongodb.name }}-service
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Values.mongodb.name }}
        image: {{ .Values.mongodb.image.name }}:{{ .Values.mongodb.image.tag }}
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: {{ .Values.mongodb.name }}-data
            mountPath: "/data/db"
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.mongodb.name }}-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: {{ .Values.mongodb.volume.size }}
