all:
  hosts:
    cloudplatform:
      ansible_host: 20.199.84.176
      ip: 10.2.0.5
      access_ip: 10.2.0.5
  children:
    kube_control_plane:
      hosts:
        cloudplatform:
    kube_node:
      hosts:
        cloudplatform:
    etcd:
      hosts:
        cloudplatform:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
