apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.licence.name }}-configmap
  labels:
    app: {{ .Values.app}}
  namespace: {{ .Values.namespace }}
data:
  database_url: mongodb://{{ .Values.mongodb.name }}-service.{{ .Values.namespace }}.svc.cluster.local.:27017

