apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-routes
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  apisix.yaml: |-
    routes:
      -
        uri: /identity/*
        upstream:
            nodes:
                    "cloud-platform-keycloak.{{ .Release.Namespace }}.svc.cluster.local:80": 1
            type: roundrobin
        priority: 200
      -
        uri: /*
        upstream:
            nodes:
                    "superset.superset.svc.cluster.local:8088": 1
            type: roundrobin
        priority: 201
      -
        uri: /grafana/*
        upstream:
            nodes:
                    "grafana.{{ .Release.Namespace }}.svc.cluster.local:80": 1
            type: roundrobin
        priority: 201
      -
        uri: /ksql/*
        upstream:
            nodes:
                    "cloud-platform-cp-ksql-server.{{ .Release.Namespace }}.svc.cluster.local:8088": 1
            type: roundrobin
        priority: 201
        plugins:
          proxy-rewrite:
            regex_uri : ["^/ksql/(.*)", "/$1"]
      -
        uri: /registry/*
        upstream:
            nodes:
                    "cloud-platform-cp-schema-registry.{{ .Release.Namespace }}.svc.cluster.local:8081": 1
            type: roundrobin
        priority: 201
        plugins:
          proxy-rewrite:
            regex_uri : ["^/registry/(.*)", "/$1"]
      -
        uri: /kafka-ui/*
        upstream:
            nodes:
                    "kafka-ui.{{ .Release.Namespace }}.svc.cluster.local:80": 1
            type: roundrobin
        priority: 201
      -
        uri: /api/v1/*
        upstream:
            nodes:
                    "apiserver.{{ .Release.Namespace }}.svc.cluster.local:5000": 1
            type: roundrobin
        priority: 201
        plugins:
            openid-connect:
                access_token_in_authorization_header: false
                client_id: {{ .Values.global.oauth2.apisix.client }}
                client_secret: {{ .Values.global.oauth2.apisix.secret }}
                discovery: >-
                        https://{{  .Values.global.oauth2.issuer }}/realms/{{ .Values.global.oauth2.realm }}/.well-known/openid-configuration
                introspection_endpoint: >-
                        https://{{  .Values.global.oauth2.issuer }}/realms/{{ .Values.global.oauth2.realm }}/protocol/openid-connect/token/introspect
                scope: "openid profile"
                bearer_only: false
                use_jwks: true
                set_userinfo_header: true
                realm: {{ .Values.global.oauth2.realm }}
                introspection_endpoint_auth_method: client_secret_post
                redirect_uri: "/api/v1/"
            cors:
                allow_origins: "*"
      -
        uri: /user-business-info/*
        upstream:
            nodes:
                    "user-informations.{{ .Release.Namespace }}.svc.cluster.local:8080": 1
            type: roundrobin
        priority: 201
        plugins:
            openid-connect:
                access_token_in_authorization_header: false
                client_id: {{ .Values.global.oauth2.apisix.client }}
                client_secret: {{ .Values.global.oauth2.apisix.secret }}
                discovery: >-
                        https://{{  .Values.global.oauth2.issuer }}/realms/{{ .Values.global.oauth2.realm }}/.well-known/openid-configuration
                introspection_endpoint: >-
                        https://{{  .Values.global.oauth2.issuer }}/realms/{{ .Values.global.oauth2.realm }}/protocol/openid-connect/token/introspect
                scope: "openid profile"
                bearer_only: false
                realm: {{ .Values.global.oauth2.realm }}
                introspection_endpoint_auth_method: client_secret_post
                redirect_uri: "/user-business-info/redirect"
            cors:
                allow_origins: "*"
      -
        uri: /prometheus/*
        upstream:
            nodes:
                    "kube-prometheus-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090": 1
            type: roundrobin
        priority: 201
        plugins:
            openid-connect:
                access_token_in_authorization_header: false
                client_id: {{ .Values.global.oauth2.apisix.client }}
                client_secret: {{ .Values.global.oauth2.apisix.secret }}
                discovery: >-
                        https://{{  .Values.global.oauth2.issuer }}/realms/{{ .Values.global.oauth2.realm }}/.well-known/openid-configuration
                introspection_endpoint: >-
                        https://{{  .Values.global.oauth2.issuer }}/realms/{{ .Values.global.oauth2.realm }}/protocol/openid-connect/token/introspect
                scope: "openid profile"
                bearer_only: false
                realm: {{ .Values.global.oauth2.realm }}
                introspection_endpoint_auth_method: client_secret_post
                redirect_uri: "/prometheus/redirect"
            cors:
                allow_origins: "*"

    #END
