apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: {{ .Values.global.cloudplatform.hostname }}-tls
 namespace: {{ .Release.Namespace }}
 labels:
   app.kubernetes.io/managed-by: Helm
spec:
  dnsNames:
    - {{ .Values.global.cloudplatform.hostname }}
  issuerRef:
    kind: Issuer
    name: {{ .Values.global.tls.issuer }}
  secretName: {{ .Values.global.cloudplatform.hostname }}-tls
  usages:
     - digital signature
     - key encipherment
