apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
stringData:
  root-password: {{ .Values.global.cloudplatform.dbrootpassword }}
  password: {{ .Values.global.cloudplatform.password }}
  username: {{ .Values.global.cloudplatform.username }}
