apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: keycloak
      owner: {{ .Values.global.keycloak.postgresql.username }}
      secret:
        name: keycloak-db-secret

  storage:
    size: 8Gi
