apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ferretdb-cluster
  labels:
    app.kubernetes.io/managed-by: Helm

spec:
  instances: {{ .Values.global.ferretdb.replicas }}
  imageName: ghcr.io/ferretdb/postgres-documentdb:{{ .Values.global.ferretdb.postgresqlimagetag }}
  postgresUID: 999
  postgresGID: 999
  superuserSecret: 
    name: ferretdb 
  enableSuperuserAccess: true

  bootstrap:
    initdb:
      postInitSQL:
        - 'CREATE EXTENSION IF NOT EXISTS documentdb CASCADE;'


  storage:
    size: 2Gi

  postgresql:
    shared_preload_libraries:
      - pg_cron
      - pg_documentdb_core
      - pg_documentdb
    parameters:
      cron.database_name: 'postgres'
