apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  instances: {{ .Values.global.keycloak.postgresql.replicas }}

  bootstrap:
    initdb:
      database: keycloak
      owner: {{ .Values.global.keycloak.postgresql.username }}
      secret:
        name: keycloak-db-secret

  storage:
    size: 8Gi
