apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.keycloak.postgresql.username }}
  password: {{ .Values.global.keycloak.postgresql.password }}
