apiVersion: v1
kind: Secret
metadata:
        name: {{ .Values.keycloak.name }}-secret
        namespace: {{ .Values.namespace }}
type: Opaque
data:
        username: {{ .Values.secrets.keycloak.username | b64enc}}
        password: {{ .Values.secrets.keycloak.password | b64enc }}
        db-username: {{ .Values.secrets.db.username | b64enc }}
        db-password: {{ .Values.secrets.db.password | b64enc }}
